name: Coverage
on: [pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    env:
      # https://turbo.build/repo/docs/ci/github-actions#remote-caching
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - run: git --version
      
      # workaround checkout
      - run: git clone --depth 1 --branch ${{ github.ref_name }} --single-branch https://github.com/ampcpmgp/elemental-sea.git .

      # actions/checkout causes error
      # https://github.com/ampcpmgp/elemental-sea/actions/runs/8670351694/job/23778249261]
      #
      # try to below, but not working
      # https://github.com/actions/checkout/issues/395
      # 
      # - uses: action/checkout@v4

      # https://bun.sh/guides/runtime/cicd
      - uses: oven-sh/setup-bun@v1

      # Run
      - run: bun install
      - run: bun run coverage

      - name: Report Coverage
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2
