name: Type Check
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    env:
      # https://turbo.build/repo/docs/ci/github-actions#remote-caching
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - run: git --version
      
      # workaround checkout
      - run: git clone --depth 1 --branch ${{ github.ref_name }} --single-branch https://github.com/ampcpmgp/elemental-sea.git .

      # actions/checkout causes error
      # https://github.com/ampcpmgp/elemental-sea/actions/runs/8670351694/job/23778249261]
      #
      # try to below, but not working
      # https://github.com/actions/checkout/issues/395
      # 
      # - uses: action/checkout@v4

      # https://bun.sh/guides/runtime/cicd
      - uses: oven-sh/setup-bun@v1

      # Run
      - run: bun install
      - run: bun run type-check
